
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    jpa:
      show-sql: true
  rabbitmq:
    host: 39.98.164.182
    port: 6661
    username: guest
    password: guest
  redis:
    host: 39.98.164.182
    port: 6666
    password: 199192abc     

server:
  port: 8088

#PRODUCT:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
branch: pro234
person:
   name: yangrui
   age: 27
